"""Direct product of 1-generated RSI ICRPs, then F(1) in that variety.

Run with jython (from any directory):

    jython free_rsi_icrp_product.py
    jython free_rsi_icrp_product.py -o model_outputs/rsi_icrp_F1.ua

The product of the loaded algebras has about 2e8 elements, so this does
not call FreeAlgebra(product, 1) on that product (that would power a
193-million-element algebra). It uses the equivalent Birkhoff
construction: F(1) is the subalgebra of prod_i A_i^{|A_i|} generated by
the concatenated identity tuples. That is F_V(1) for V = HSP(product).
"""
import os
import re
import sys

UACALC_DIR = os.path.expanduser("~/uacalc")
sys.path.append(os.path.join(UACALC_DIR, "uacalc.jar"))
sys.path.append(UACALC_DIR)

from jarray import array
from org.uacalc.alg import BigProductAlgebra, FreeAlgebra, ProductAlgebra
from org.uacalc.io import AlgebraIO
from org.uacalc.util import IntArray
from mace4 import to_alg

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR = os.path.join(SCRIPT_DIR, "model_outputs")
DEFAULT_OUT = os.path.join(MODEL_DIR, "rsi_icrp_one_generated_product_F1.ua")
ONE_GENERATED_RE = re.compile(r"^rsi_icrp-(\d+)_one_generated\.model$")


def one_generated_model_paths(model_dir):
    paths = []
    for name in os.listdir(model_dir):
        match = ONE_GENERATED_RE.match(name)
        if match:
            paths.append((int(match.group(1)), os.path.join(model_dir, name)))
    paths.sort()
    return [path for _, path in paths]


def load_one_generated_algebras(model_dir):
    algebras = []
    for path in one_generated_model_paths(model_dir):
        base = os.path.basename(path).replace("_one_generated.model", "")
        n_here = 0
        for alg in to_alg(path):
            n_here += 1
            alg.setName("%s#%d" % (base, n_here))
            algebras.append(alg)
            print "loaded %s  size %d  ops %s" % (
                alg.getName(),
                alg.cardinality(),
                [op.symbol() for op in alg.operations()],
            )
        if n_here == 0:
            print "skipped empty file %s" % path
    return algebras


def free_one_over_product(algebras, name):
    """F(1) in HSP(A1 x ... x Ak), via prod_i A_i^{|A_i|}."""
    powers = array([alg.cardinality() for alg in algebras], "i")
    ambient = BigProductAlgebra(algebras, powers)
    coords = []
    for alg in algebras:
        coords.extend(range(alg.cardinality()))
    generator = IntArray(array(coords, "i"))
    print "ambient coordinates: %d  (sum of factor sizes)" % len(coords)
    print "computing 1-generated subalgebra of the ambient product ..."
    universe = ambient.sgClose([generator])
    return FreeAlgebra(name, ambient, [generator], universe)


def parse_args(argv):
    out_path = DEFAULT_OUT
    i = 1
    while i < len(argv):
        arg = argv[i]
        if arg in ("-o", "--output"):
            i += 1
            if i >= len(argv):
                raise Exception("missing path after %s" % arg)
            out_path = argv[i]
        elif arg.startswith("-"):
            raise Exception("unknown option: %s" % arg)
        else:
            out_path = arg
        i += 1
    if not os.path.isabs(out_path):
        out_path = os.path.join(SCRIPT_DIR, out_path)
    return out_path


if __name__ == "__main__":
    out_path = parse_args(sys.argv)
    out_dir = os.path.dirname(out_path)
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir)

    print "model directory: %s" % MODEL_DIR
    algebras = load_one_generated_algebras(MODEL_DIR)
    if not algebras:
        raise Exception("no 1-generated rsi_icrp models found in %s" % MODEL_DIR)

    sizes = [alg.cardinality() for alg in algebras]
    print "loaded %d algebras, sizes %s" % (len(algebras), sizes)

    product = ProductAlgebra("product of 1-generated RSI ICRPs", algebras)
    print "direct product cardinality: %d" % product.cardinality()
    print "factors: %s" % [alg.getName() for alg in product.factors()]

    free_name = "F(1) over product of 1-generated RSI ICRPs"
    free_alg = free_one_over_product(list(product.factors()), free_name)
    print "F(1) cardinality: %d" % free_alg.cardinality()

    AlgebraIO.writeAlgebraFile(free_alg, out_path)
    print "wrote %s" % out_path
