"""Filter a Mace4 model file to those algebras that are 1-generated.

An algebra is 1-generated when the subalgebra generated by some single
element equals the whole universe (via UACalc's ``sub().sg``).

Also writes a PDF with fusion / poset Hasse diagrams, the ``\\`` Cayley
table, and the singleton generators for each kept algebra.
"""

from __future__ import annotations

import re
from pathlib import Path

from pyp9m4 import Model, parse_models_from_file
from uacalc_lib import io as ua_io


def one_generators(algebra) -> list[int]:
    """Return all elements whose generated subalgebra is the whole algebra."""
    n = algebra.cardinality()
    sub = algebra.sub()
    return [i for i in range(n) if sub.sg([i]).size() == n]


def is_one_generated(algebra) -> bool:
    """Return True if some singleton generates the whole algebra."""
    return bool(one_generators(algebra))


def _arrow_table_cells(model: Model) -> list[list[str]]:
    """Cayley table for the residual operation ``\\``."""
    arrow = model.as_function("\\")
    n = model.domain_size
    return [[str(arrow(i, j)) for j in range(n)] for i in range(n)]


def draw_one_generated(model: Model, generators: list[int]):
    """Draw fusion, poset, ``\\`` table, and generators for one algebra."""
    import matplotlib.pyplot as plt

    from draw_orders import draw_graph
    from icrp import get_graphs

    leq_graph, fusion_leq_graph = get_graphs(model)
    name_match = re.search(r"number\s*=\s*(\d+)", model.raw)
    name = name_match.group(1) if name_match else "?"
    n = model.domain_size
    gen_set = set(generators)

    # Generators highlighted orange; others light blue
    node_colors = ["orange" if i in gen_set else "lightblue" for i in range(n)]

    fig = plt.figure(figsize=(11, 7.5), layout="constrained")
    gs = fig.add_gridspec(2, 2, height_ratios=[1.35, 1.0])
    ax_fusion = fig.add_subplot(gs[0, 0])
    ax_poset = fig.add_subplot(gs[0, 1])
    ax_table = fig.add_subplot(gs[1, :])
    ax_table.axis("off")

    draw_graph(
        ax_fusion,
        fusion_leq_graph,
        "Fusion SemiLattice",
        node_colors=node_colors,
    )
    draw_graph(ax_poset, leq_graph, "Poset", node_colors=node_colors)

    labels = [str(i) for i in range(n)]
    cells = _arrow_table_cells(model)
    table = ax_table.table(
        cellText=cells,
        rowLabels=labels,
        colLabels=labels,
        loc="center",
        cellLoc="center",
    )
    table.auto_set_font_size(False)
    fontsize = 10 if n <= 8 else (8 if n <= 12 else 6)
    table.set_fontsize(fontsize)
    table.scale(1.0, 1.4)
    header_color = "#eceff1"
    gen_color = "#ffe0b2"
    for (row, col), cell in table.get_celld().items():
        cell.set_edgecolor("#b0bec5")
        if row == 0 or col == -1:
            cell.set_facecolor(header_color)
            cell.get_text().set_fontweight("bold")
            # Highlight generator rows/columns
            if col == -1 and row > 0 and (row - 1) in gen_set:
                cell.set_facecolor(gen_color)
            if row == 0 and col >= 0 and col in gen_set:
                cell.set_facecolor(gen_color)
            continue
    if (0, -1) in table.get_celld():
        table[0, -1].get_text().set_text("\\")
        table[0, -1].get_text().set_fontweight("bold")

    ax_table.set_title(r"Arrow table  (row \ column)", fontsize=10, pad=8)
    fig.suptitle(
        f"model{name}   generators = {generators}",
        fontsize=14,
        fontweight="bold",
    )
    return fig


def one_generated_pdf(
    models_and_gens: list[tuple[Model, list[int]]],
    pdf_filename: Path | str,
) -> None:
    """Write one PDF page per (model, generators) pair."""
    import matplotlib.backends.backend_pdf
    import matplotlib.pyplot as plt

    from draw_orders import _terminal_status

    pdf_path = Path(pdf_filename)
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    pdf = matplotlib.backends.backend_pdf.PdfPages(filename=str(pdf_path))
    for i, (model, gens) in enumerate(models_and_gens):
        name_match = re.search(r"number\s*=\s*(\d+)", model.raw)
        name = name_match.group(1) if name_match else "?"
        _terminal_status(f"PDF page {i + 1}: drawing model {name}...")
        fig = draw_one_generated(model, gens)
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)
    print()
    pdf.close()


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Keep only 1-generated models and draw them to PDF."
    )
    parser.add_argument("-i", "--input", type=str, required=True)
    parser.add_argument("-o", "--output", type=str, default=None)
    parser.add_argument(
        "--pdf",
        type=str,
        default=None,
        help="PDF path (default: output/<stem>_one_generated.pdf)",
    )
    parser.add_argument(
        "--no-pdf",
        action="store_true",
        help="Skip PDF generation; only write the filtered .model file.",
    )
    args = parser.parse_args()

    model_filename = Path(args.input)
    if args.output is None:
        output_folder = Path("model_outputs")
        output_folder.mkdir(exist_ok=True)
        output_filename = output_folder / f"{model_filename.stem}_one_generated.model"
    else:
        output_filename = Path(args.output)
        output_filename.parent.mkdir(parents=True, exist_ok=True)

    if args.pdf is None:
        pdf_filename = Path("output") / f"{model_filename.stem}_one_generated.pdf"
    else:
        pdf_filename = Path(args.pdf)

    kept: list[tuple[Model, list[int]]] = []
    total = 0
    with open(output_filename, "w", encoding="utf-8", newline="\n") as out:
        for model, algebra in zip(
            parse_models_from_file(model_filename),
            ua_io.Mace4Reader.parse_algebra_list_from_file(str(model_filename)),
        ):
            total += 1
            gens = one_generators(algebra)
            if not gens:
                continue
            kept.append((model, gens))
            print(
                f"kept {algebra.name()} "
                f"(size {algebra.cardinality()}, generators {gens})"
            )
            text = model.raw
            if not text.endswith("\n"):
                text += "\n"
            out.write(text)

    print(f"wrote {len(kept)}/{total} one-generated models to {output_filename}")

    if not args.no_pdf and kept:
        one_generated_pdf(kept, pdf_filename)
        print(f"PDF saved to {pdf_filename}")
    elif not kept:
        print("no one-generated models; skipped PDF")
