"""Filter a Mace4 model file to those algebras that are 1-generated.

An algebra is 1-generated when the subalgebra generated by some single
element equals the whole universe (via UACalc's ``sub().sg``).
"""

from __future__ import annotations

from pathlib import Path

from pyp9m4 import parse_models_from_file
from uacalc_lib import io as ua_io


def one_generators(algebra) -> list[int]:
    """Return all elements whose generated subalgebra is the whole algebra."""
    n = algebra.cardinality()
    sub = algebra.sub()
    return [i for i in range(n) if sub.sg([i]).size() == n]


def is_one_generated(algebra) -> bool:
    """Return True if some singleton generates the whole algebra."""
    return bool(one_generators(algebra))


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Keep only 1-generated models from a Mace4 .model file."
    )
    parser.add_argument("-i", "--input", type=str, required=True)
    parser.add_argument("-o", "--output", type=str, default=None)
    args = parser.parse_args()

    model_filename = Path(args.input)
    if args.output is None:
        output_folder = Path("model_outputs")
        output_folder.mkdir(exist_ok=True)
        output_filename = output_folder / f"{model_filename.stem}_one_generated.model"
    else:
        output_filename = Path(args.output)
        output_filename.parent.mkdir(parents=True, exist_ok=True)

    kept = 0
    total = 0
    with open(output_filename, "w", encoding="utf-8", newline="\n") as out:
        for model, algebra in zip(
            parse_models_from_file(model_filename),
            ua_io.Mace4Reader.parse_algebra_list_from_file(str(model_filename)),
        ):
            total += 1
            gens = one_generators(algebra)
            if not gens:
                continue
            kept += 1
            print(
                f"kept {algebra.name()} "
                f"(size {algebra.cardinality()}, generators {gens})"
            )
            text = model.raw
            if not text.endswith("\n"):
                text += "\n"
            out.write(text)

    print(f"wrote {kept}/{total} one-generated models to {output_filename}")
