<?xml version="1.0"?>
<algebra>
  <basicAlgebra>
    <algName>model4169931</algName>
    <cardinality>10</cardinality>
    <universe>
      <elem>9</elem>
      <elem>1</elem>
      <elem>0</elem>
      <elem>4</elem>
      <elem>5</elem>
      <elem>2</elem>
      <elem>6</elem>
      <elem>7</elem>
      <elem>8</elem>
      <elem>3</elem>
    </universe>
    <operations>
      <op>
        <opSymbol>
          <opName>*</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">0,1,2,3,4,5,6,7,8,9</row>
            <row r="[1]">1,1,1,3,4,5,6,7,1,1</row>
            <row r="[2]">2,1,2,3,4,5,6,7,2,1</row>
            <row r="[3]">3,3,3,3,3,3,3,3,3,3</row>
            <row r="[4]">4,4,4,3,4,5,7,7,4,4</row>
            <row r="[5]">5,5,5,3,5,5,3,3,5,5</row>
            <row r="[6]">6,6,6,3,7,3,6,7,6,6</row>
            <row r="[7]">7,7,7,3,7,3,7,7,7,7</row>
            <row r="[8]">8,1,2,3,4,5,6,7,8,9</row>
            <row r="[9]">9,1,1,3,4,5,6,7,9,9</row>
          </intArray>
        </opTable>
      </op>
      <op>
        <opSymbol>
          <opName>\</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">0,3,3,2,3,6,5,5,3,3</row>
            <row r="[1]">1,2,1,2,2,2,2,2,1,2</row>
            <row r="[2]">2,2,2,2,2,2,2,2,2,2</row>
            <row r="[3]">3,3,3,2,3,6,5,5,3,3</row>
            <row r="[4]">4,4,4,2,2,2,4,2,4,4</row>
            <row r="[5]">5,5,5,2,5,2,5,5,5,5</row>
            <row r="[6]">6,6,6,2,6,6,2,2,6,6</row>
            <row r="[7]">7,7,7,2,6,6,4,2,7,7</row>
            <row r="[8]">8,7,7,2,6,6,4,2,8,8</row>
            <row r="[9]">9,7,7,2,6,6,4,2,9,8</row>
          </intArray>
        </opTable>
      </op>
      <op>
        <opSymbol>
          <opName>e</opName>
          <arity>0</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row>0</row>
          </intArray>
        </opTable>
      </op>
    </operations>
  </basicAlgebra>
</algebra>
