<?xml version="1.0"?>
<algebra>
  <basicAlgebra>
    <algName>model34</algName>
    <cardinality>5</cardinality>
    <universe>
      <elem>1</elem>
      <elem>3</elem>
      <elem>0</elem>
      <elem>2</elem>
      <elem>4</elem>
    </universe>
    <operations>
      <op>
        <opSymbol>
          <opName>*</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">0,1,2,3,4</row>
            <row r="[1]">1,1,1,3,4</row>
            <row r="[2]">2,1,2,3,4</row>
            <row r="[3]">3,3,3,3,3</row>
            <row r="[4]">4,4,4,3,4</row>
          </intArray>
        </opTable>
      </op>
      <op>
        <opSymbol>
          <opName>\</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">0,3,3,4,3</row>
            <row r="[1]">1,2,1,4,3</row>
            <row r="[2]">2,2,2,4,3</row>
            <row r="[3]">3,3,3,4,3</row>
            <row r="[4]">4,4,4,4,4</row>
          </intArray>
        </opTable>
      </op>
      <op>
        <opSymbol>
          <opName>e</opName>
          <arity>0</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row>0</row>
          </intArray>
        </opTable>
      </op>
    </operations>
  </basicAlgebra>
</algebra>
